= Nova Framework

image:https://img.shields.io/github/v/tag/MarcelCoding/nova?label=latest%20version&style=flat-square[latest version,link=https://github.com/MarcelCoding/nova/releases]
image:https://img.shields.io/github/workflow/status/MarcelCoding/nova/CI?label=CI&style=flat-square[CI,link=https://github.com/MarcelCoding/nova/actions]

Nova Framework is a framework on top of spring boot.
It aims to provide nice additions to the spring ecosystem.

== Getting Started

To add it to your project just add this repository and thees dependencies.
To keep your bundle size small it is recommended to only add the modules witch you are need.
Dependencies between modules are resolved automatically.
Keep in mind that you still need a stand-alone spring boot application to start.
You can use the https://start.spring.io/[Spring Initializer].
Nova aims to provide out of the box compatibility for https://github.com/spring-projects-experimental/spring-native/[spring native].

Currently, the latest version is:

image:https://img.shields.io/github/v/tag/MarcelCoding/nova?label=latest%20version&style=flat-square[latest version,link=https://github.com/MarcelCoding/nova/releases]

[source,groovy]
----
repositories {
  mavenCentral {
    content { excludeGroup('de.m4rc3l.nova') }
  }
  maven {
    url 'https://raw.githubusercontent.com/getnova/maven/main'
    content { includeGroup('de.m4rc3l.nova') }
  }
}

dependencies {
  implementation 'de.m4rc3l.nova:nova-api:<version>'
  implementation 'de.m4rc3l.nova:nova-api-rest:<version>'
  implementation 'de.m4rc3l.nova:nova-api-ws:<version>'
  implementation 'de.m4rc3l.nova:nova-cdn:<version>'
  implementation 'de.m4rc3l.nova:nova-core:<version>'
  implementation 'de.m4rc3l.nova:nova-data-jpa:<version>'
  implementation 'de.m4rc3l.nova:nova-web:<version>'
}
----

== Modules

The documentation to all modules can be found hear:

|===
|Name|Description|Reference Doc|Api Doc

|nova-api[-rest/-ws]
|System to implement rest api's over http and websockets.
|WIP
|WIP

|nova-core
|Core utilities for all other modules and your application.
|WIP
|WIP

|nova-data-jpa
|A collection of utilities for the Java EE JPA specification
|WIP
|WIP

|nova-web
|Reactive http client and server implementations on top of https://github.com/reactor/reactor-netty[reactor-netty].
|WIP
|WIP
|===
